apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
type: kubernetes.io/tls
data:
  # values are base64 encoded, which obscures them but does NOT provide
  # any useful level of confidentiality
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUY3ekNDQTllZ0F3SUJBZ0lVTHJETG5wdW5t
    d0w4NWlUSGExU3d5UEpNbFBzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZWXhDekFKQmdOVkJBWVRB
    bGhZTVJJd0VBWURWUVFJREFsVGRHRjBaVTVoYldVeEVUQVBCZ05WQkFjTQpDRU5wZEhsT1lXMWxN
    UlF3RWdZRFZRUUtEQXREYjIxd1lXNTVUbUZ0WlRFYk1Ca0dBMVVFQ3d3U1EyOXRjR0Z1CmVWTmxZ
    M1JwYjI1T1lXMWxNUjB3R3dZRFZRUUREQlJEYjIxdGIyNU9ZVzFsVDNKSWIzTjBibUZ0WlRBZUZ3
    MHkKTkRFd01Ua3dOakkxTkROYUZ3MHpOREV3TVRjd05qSTFORE5hTUlHR01Rc3dDUVlEVlFRR0V3
    SllXREVTTUJBRwpBMVVFQ0F3SlUzUmhkR1ZPWVcxbE1SRXdEd1lEVlFRSERBaERhWFI1VG1GdFpU
    RVVNQklHQTFVRUNnd0xRMjl0CmNHRnVlVTVoYldVeEd6QVpCZ05WQkFzTUVrTnZiWEJoYm5sVFpX
    TjBhVzl1VG1GdFpURWRNQnNHQTFVRUF3d1UKUTI5dGJXOXVUbUZ0WlU5eVNHOXpkRzVoYldVd2dn
    SWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJSwpBb0lDQVFDOVRkczY5d1AwWmxOaktH
    TWhVa0dic3lxaU5QTU4rTmVOUFRLWEpOdFJOUXFRR1F3SWE3Rit3MHdrCkl1TnduSHp0ZnNrV1Bt
    S0lvVTBWQzVGOFk1V1czSExZNGUxRU9PQlJjTVo5RE5Qb1hmYTFMVmZGMDd2QWM3UTUKUlhiSURV
    dTByMXIzemlPWGl5dTVrOXNHZXplcGRlcGhYWTl4eG5lUVIyT2QrSlNPM3M0bXFBTnlhaS9TRFE2
    QQpkQmhQMGZsZjl5djJBdUFXUzFPY3p5YXJYMDVmblR1eDNLR1RGTStUU2RkaCtEczJ4ZWlrNXFV
    bXRVRHU5dUJsCkRqZTRhU295aStBVW96NFkxanBLdWc4ZE9xV0UyTEkrZEY4cEE0bjBoSC9CczdL
    VUtlZzltWGNIUE41aUFWL0MKTDZwY1VUV09jNkVaSXFHelJJS0lkUWs2UXZlTWc0RndRbHJMdDFK
    MDdlNDZsTTRQSk9ueURiSEFiOVhGZ2RVTwpncVpDZFpEVFNtdC9EdEp1OXBoamszcFZEV0t4VjBx
    cDBEYnFkWm5xMGR1ZXZuN0ZFajkzK3N4dzRXM3QrQlg3CjJlaCsySWUrU2d4Y2NXVUtuVXBNTFRG
    ZU9oYUJyMnhHZ2RGWUxTNmNoeTRxOHJQUVJIZmFzUUxTR0xBWGs1L2UKWiszc0RrTENJWTIrWGdt
    MVpZRlZMNnJiS1ROTVlieWJZTFNleDAvdjEraGdYUkE4cGM4NDVoWEgrY0RzT0hYYgpQaitXRWZT
    NmlhbjVKQnByNGZLT0NPa05VeFd5Z3gzdVdWVmhBeGxiU01nZnlMSTkzUEl5L0pPV3hISDhuWmVY
    CllNMVViOWlQODRFT1hwbFhERWdnSXdMRVRuZncyK3FoVkplSkF1OFJ1cW5HT2gyVmF3SURBUUFC
    bzFNd1VUQWQKQmdOVkhRNEVGZ1FVenUxWHBFUmhucUtpLytlejlBS1Fua0tsbUtzd0h3WURWUjBq
    QkJnd0ZvQVV6dTFYcEVSaApucUtpLytlejlBS1Fua0tsbUtzd0R3WURWUjBUQVFIL0JBVXdBd0VC
    L3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFnRUFuWjF6OXliWUUzUW1nazRSdmppZFN0eWgyUEwr
    M0dWaG1Db0tES2xJNUFncFFJU1ZDd2NzVFhCUFRCQXQKSnJFWDJUMWFnQ3NZTUNkanFDLzFkSW4z
    T2dMazNLa3VNQm5sYUVsc2hOTmtvRTUyVWkrc2EwSjhHSTRsem5zVApkQktqOC8vTDhNYS9wN21a
    dkxrb2xNTFRCZGdPRG1BNlN6QmFlTW0rL3pkaHdVODdlaWFBZkxUd3ZKbGtLMWhCCjZjRVRXYWVH
    RHhjL1QwVWVYQVBVeFB0Yjc5U2JIMFVmS1p0SHF2MHRWUExUSzhLWmxCVjd5VCt4VmtwSFpZdHUK
    Zi8zV0REMStYL3RaNHJVbjR3eEhsTVhpL0VaOWVSY2hPaHoxZFpqUXlXSHVGSFFXMGluL1JldlB4
    UzZGQmtJRgp6SndFWjR4VUJwOWVtMW1NNmk4cjBMNVVCdVFGN2lISFVOYkVEemorQm40MDFERGw2
    OVhISlpGanlhSk9senJKCjlESDd1S2hVZk52ZzlnUmhuWDNOby9SZHVMVUMxL0hXZnd5NmNZTUpD
    b2xrOVAxQVovWmZJMUxTYXBKSS9xREEKZ0E0WmJnNCsxb1hjL2l3M2tTbzErYWVuUUVYTmJPU1lx
    aUIwQ2RRcURLdDdqajFIYW02U0FhUlNKc0dCT05iUQo2TXk2Sm9TTXZSQUJLOGxuSS9HTDU5Q0xo
    TVEyUWZ0K1FkQnBrWFJpR3FtbmFieDlxSWRFUEE1bXp1SVRmTkRGCmtSeGQ2YUJYQ214T1F6SkNB
    QVRkbkxJa3A2L20zUFcxcS8zTitlcC9UeVNQaWVleFdTR043cGtnd2M0SzQ0dWQKZ1pEeVpKMG5K
    RDVkWWxHWEk1MjNBMHUvbHpvZ2NGbW1VQUhCY0k3Y1dOQ05mMjA9Ci0tLS0tRU5EIENFUlRJRklD
    QVRFLS0tLS0K

  # In this example, the key data is not a real PEM-encoded private key
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRd0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQ1Mwd2dna3BBZ0VBQW9JQ0FRQzlUZHM2OXdQMFpsTmoKS0dNaFVrR2JzeXFpTlBNTitOZU5Q
    VEtYSk50Uk5RcVFHUXdJYTdGK3cwd2tJdU53bkh6dGZza1dQbUtJb1UwVgpDNUY4WTVXVzNITFk0
    ZTFFT09CUmNNWjlETlBvWGZhMUxWZkYwN3ZBYzdRNVJYYklEVXUwcjFyM3ppT1hpeXU1Cms5c0dl
    emVwZGVwaFhZOXh4bmVRUjJPZCtKU08zczRtcUFOeWFpL1NEUTZBZEJoUDBmbGY5eXYyQXVBV1Mx
    T2MKenlhclgwNWZuVHV4M0tHVEZNK1RTZGRoK0RzMnhlaWs1cVVtdFVEdTl1QmxEamU0YVNveWkr
    QVVvejRZMWpwSwp1ZzhkT3FXRTJMSStkRjhwQTRuMGhIL0JzN0tVS2VnOW1YY0hQTjVpQVYvQ0w2
    cGNVVFdPYzZFWklxR3pSSUtJCmRRazZRdmVNZzRGd1Fsckx0MUowN2U0NmxNNFBKT255RGJIQWI5
    WEZnZFVPZ3FaQ2RaRFRTbXQvRHRKdTlwaGoKazNwVkRXS3hWMHFwMERicWRabnEwZHVldm43RkVq
    OTMrc3h3NFczdCtCWDcyZWgrMkllK1NneGNjV1VLblVwTQpMVEZlT2hhQnIyeEdnZEZZTFM2Y2h5
    NHE4clBRUkhmYXNRTFNHTEFYazUvZVorM3NEa0xDSVkyK1hnbTFaWUZWCkw2cmJLVE5NWWJ5YllM
    U2V4MC92MStoZ1hSQThwYzg0NWhYSCtjRHNPSFhiUGorV0VmUzZpYW41SkJwcjRmS08KQ09rTlV4
    V3lneDN1V1ZWaEF4bGJTTWdmeUxJOTNQSXkvSk9XeEhIOG5aZVhZTTFVYjlpUDg0RU9YcGxYREVn
    ZwpJd0xFVG5mdzIrcWhWSmVKQXU4UnVxbkdPaDJWYXdJREFRQUJBb0lDQUJ5ckhzbFdRVllRN1Ez
    MlB0VDhCUTJVClc1K0hEMHdOWkc5eVZpZ0huK016ZWk4S2JBVVdjaUgxWjZHTld3NWgxSldPL3Rz
    TWhaV1ZmL3Z3N1k1OThsaVAKZUNFYVRmbG45Nmk5d0lHTm9NWHUvUDdCS0NyQWZ3Mk5PRHo0SlIz
    MHpZTkdqeXM2SDYvQ2x0T2E3YStVbDRCbAphQ0pvcmVHWUllRkt2bTVkQi9wL0NZOVhJSGFDV0Uy
    aVJwRHpnLzhLbUk2TSt5NWRqeHd4T2k5a084SDJSQU04CjU1NXZBRlVxOEtpb3BTS2tHaXVZV3p3
    bDVkcnYxaTZhV3E5VE1PTVBvaUZYaDQ3NGpkM3JDNWJuaUlSdnJrTnAKSWMxTmlGL0l0bXErYWk2
    bWpTUGRHTnZEVXdCWW1vRVRIakpsVDVKOWhmUFYxUTdlYk1pZVZucGQ1eERZdFc1aQpGekdYQWJS
    VlZ3cjhMMmwvcTB3RXdUVlJ3SU9sVWZQQ2lrbkFZZkxuM3llRDNwTW1PWUUvY1pLMVJvMGVkcUNG
    CkM2b2ZNdFhaMTN2U0QweUNBRU1ZdzRuNHJpUlJLaVRiMFdQMUx6ZmtlNzl6T2xnT2lsdlovWmhP
    bjBhWWw1cTUKWjBWN1NtUVNNcnNqNFpEc3JvZ2FKYkVKc09TMXNtMzlWUm4xOXlyaWJDaTU5Qzd0
    S0pid0o2eWpKcE12SFh6RgpSVFhZVDFaNUJ3UTZNUzFsWUJ3bUorUGducThaS1R5V1VPQ0VGeHYy
    VjcrTEQyTzdrcmxWclBxam5oRXlUN3ZlCjN0S2dOR0RzNWZsQ2pGT2s0eDE4S2FyT2prcHFES0tr
    bjlpUEFQdUhOQjdOQU9WU3NMWTJiQzZVR2t3VXNQU2oKeGVUdEZVZCtEcFcrTXFLblVRODVBb0lC
    QVFEM1ExcloyZzhGOE4xa2UxNkVvT2NEKzRXSzBtVnVablVDMFlqVQpvVE8yZlRseVpHMGdlRXBL
    ZkR4NzZBdVhCdGNnR0wyOVRrd2pBRGVBcTVtT2FPUC9CYjM5QlNadHo2ZzI0NG5vCjBNZkhLVHND
    NXA1K2JzQTd0cDBVdllncXB4MmVQV01vRWRZQTg3OW1mRjlsY0xib283aTVJY3JqWnhzeVRhd0wK
    YVo3R2MyM0FUNElZNDFXUmg1Z2xRSzlhcU54eU9RYWJiWUpTTDhIQ3ZHbkhCZ0tXQnpOak4xU2pG
    YTVTdVNkMgo3QXlaY1pzTHgwSmRQall4dzBGK1JGemwybkZFanlzSGJjL09nK2tTLzJ6ZEhyRDkx
    UXdmbFFXdVBqb1MrQXZrCjM2YkZGYUVRYXZVTExEYUFBbzBkeGZGOHVQNm5iYmJqZ1MyeVdheDJr
    bW8wcTRkL0FvSUJBUUREL2pvdk85d2IKc1M2aENoaERWSC8wT2JhS0dWUXpUYzZDbjZSMXVHcjJi
    WUhIS0FpWldJZ29zbXZqR2RKRk9wUk1TZzk5NXFnbwpoY3Z2bFFORmVXTkhueE5wWEN1eXE5MXlh
    dHgwTWpxU0Q5N0xNSDJTVkQ3NHNHK2N1MmhKYWVPREtoNklOSk5jCm42Rk1BbUQrSDFyYlI0Y2V6
    WmhvK0xtSG1LR09JOTB4VjdpMnBjWC9rbGZkVEFaZ1AvYmkra2ZWUWJvOExrMncKRTdCOUw3QW4z
    UElkNmtZOVYxTnZvTnFBUVBNYU5kanR3RHNMU1hyOUVQV3ZNazhITlJ5TEJsSnUyZFc4V3FEaApk
    RDd4N3B3K0JManJhZFltV1RTbzl6UndUU0ZMM0h4NVlFWHBOUXJyQTNReFVGc2VZN0NEcXcwQzdN
    b3N1cms0ClZmTG5SdEsvOElnVkFvSUJBUURvaVoydGQ5ZmRISEw1aHRTVElzZGdCWEhINXFxaHN4
    V2tPdTdXR1d5SzJTWG4Kb083SU5KaVppRkZScmg4SVA5U2RTT2RZVzRSYS9sODBVUzJ1c3BLSlNo
    c3RFMlRhclFwajVJWFVRRlZCeGxMTApIWnc5QjJjZVFWVmxKZ0lqS3RzOThEbUtlNHVwaFpLaGph
    SWh3bWtpVEtieTVRYnI2aEczc3poejJ6Y0pKNUUxCjVSQlMyNm1qbmNQR2RSajB5QTNhRml0U2pT
    Q2NybkVvOVF6OXNYZEpKU2g4ekpKNmRXOW1PTjhXaGxRckVwNWYKNjF0TVdhK2FDU2xVMkhJTmNP
    eEpMK09scnU1YUo5QlFuNHNBUVZidXdTZ1BvNVNlRThPR0IyVVlNQVdsSC94RApkbk5SdUpqZ3Rv
    V0VWSjRSVCtHZUVCNkp3dmo0M0VESG1sYnJoYzE5QW9JQkFHYnpUcXJxL1phS1BwMFd5V0hzCnEv
    MmtweTdwV1NKTjE1RWp2R2FkeFluR1FlcFVMQmdvdWZUdXE5OHgvQktqVDZ5M0ptWVMxL2ZaT0NP
    VUdaRFAKejRlYWxyNjhUTFBndFVUWnZ3MUdLUi82T0NSeFJ6U3JEaHpoeU84Q1BpaDU5Nms1WWFw
    WU82UG1zZnBVTVpDcQo5YlhEWDhXZFoxYVVlQmd5NDRIZmN0dnRZVGlINFhaNjc2NXR0ZGV2SWNk
    ZWdvY1JySHJhTTdLdTFRRWRJS0gvCjNDbzhta0swY1Q1c3R2bXhwRUQ3VWdTbytocldzVVRuT0xh
    YmJZbXlxMWlYckl0UDM0YTk4RTRkR3NkSWVFZlgKZ1M4ZmUvN08wdXVDVnNnNnE2ZkduSmZCSzFm
    eHBkZUhDK3l2Y2YySGpmdkx5TnpsZHRtQ0I3TUE2c1B6bnRaMQp5WFVDZ2dFQkFLc2FadlQxamZh
    c0p2empnNUlmNGZmblpFZjhRTVhkdDR5TkRkVGFsSkFjUUxoRllxWmk1cndaCmtkSFZPSG9VU0N4
    MXJ4NEVtN2pRYWtCei9yejVLQ21OU0NCZlhMMVpKalF6eHNsRXh5Szkvb2xNZC9Qcm41KzAKVXFi
    WHdCZnhvUkdqdjl6cU80d2JrUUtOK0l1N21hc2NaSXVUTER2Yld1TENmd085cTAzcXlVbXhJTWZ2
    VWF1cApQVUQvK2dldlJvTGZkaU5NdUtwV2JBd2UvNFdNMWRYakdQVlpoYnM0ajJjdE04YllLNDVD
    NmlLc21TWkdSaGlmCmN5bTdQeUV6cXNBS0ZqWVJFVW53UklPU2xzNEU3bjhicFU2ZmRYY0o5Y1V6
    U0NXdEJNNXNKZmhSU3JPR0JTdEwKeGQ1ZXp0bFBzYUN4NDF1anVQUmkzZ0lMN1R3SVNDbz0KLS0t
    LS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
